import React, { useMemo, useRef, useState } from 'react';
import { Upload, Loader2, Trash2, CheckCircle, XCircle } from 'lucide-react';

const bytesToSize = (bytes) => {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`;
};

const ImageDetection = () => {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState('');
  const [imgMeta, setImgMeta] = useState({ width: 0, height: 0 });
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState(null);

  const inputRef = useRef(null);

  const onPick = (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setFile(f);
    const url = URL.createObjectURL(f);
    setPreview(url);
    const img = new Image();
    img.onload = () => {
      setImgMeta({ width: img.width, height: img.height });
      URL.revokeObjectURL(img.src);
    };
    img.src = url;
    setResult(null);
  };

  const clearAll = () => {
    setFile(null);
    setPreview('');
    setResult(null);
    setImgMeta({ width: 0, height: 0 });
    if (inputRef.current) inputRef.current.value = '';
  };

  const analyze = async () => {
    if (!file) return;
    setAnalyzing(true);
    // Simulate network/processing delay
    await new Promise((r) => setTimeout(r, 2000));

    // Simple deterministic-ish confidence based on file size
    const base = (file.size % 31) + 70; // 70 - 100
    const confidence = Math.min(100, Math.max(70, base));
    const isAIGenerated = confidence >= 85; // threshold for demo

    const notesAI = [
      'Detected uniform lighting with minimal falloff typical of synthetic renders.',
      'Texture repetition and overly smooth surfaces suggest generative artifacts.',
      'Edge halos and inconsistent reflections align with AI upscaling patterns.',
    ];
    const notesReal = [
      'Natural noise distribution and lens artifacts indicate authentic capture.',
      'Lighting falloff and shadow softness are consistent with real-world optics.',
      'Micro-texture and color variance support real image characteristics.',
    ];

    const notePool = isAIGenerated ? notesAI : notesReal;
    const note = notePool[(file.size % notePool.length)];

    setResult({
      label: isAIGenerated ? 'AI-Generated' : 'Authentic',
      confidence,
      note,
    });
    setAnalyzing(false);
  };

  const confidenceColor = useMemo(() => {
    if (!result) return 'bg-blue-600';
    if (result.label === 'AI-Generated') return 'bg-red-600';
    if (result.confidence >= 90) return 'bg-green-600';
    return 'bg-green-500';
  }, [result]);

  return (
    <section id="image-detection" className="">
      <div className="mb-6">
        <h2 className="text-2xl sm:text-3xl font-semibold text-white">AI Image Detection</h2>
        <p className="text-gray-400 mt-1">Upload an image to check if it was generated by AI. We’ll analyze textures, lighting, and other signals.</p>
      </div>

      <div className="rounded-xl border border-white/10 bg-white/5 p-5">
        {/* Controls */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
          <input
            ref={inputRef}
            type="file"
            accept="image/*"
            onChange={onPick}
            className="hidden"
            id="file-input"
          />
          <label
            htmlFor="file-input"
            className="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-md font-medium bg-yellow-400 text-black hover:bg-yellow-300 cursor-pointer transition"
          >
            <Upload size={18} />
            Upload Image
          </label>

          <button
            onClick={analyze}
            disabled={!file || analyzing}
            className={`inline-flex items-center justify-center gap-2 px-4 py-2 rounded-md font-medium transition ${
              !file || analyzing ? 'bg-blue-600/40 text-blue-200 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-500 text-white'
            }`}
          >
            {analyzing ? (
              <>
                <Loader2 size={18} className="animate-spin" /> Analyzing…
              </>
            ) : (
              'Analyze'
            )}
          </button>

          {file && (
            <button
              onClick={clearAll}
              className="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-md font-medium bg-red-600 hover:bg-red-500 text-white transition"
            >
              <Trash2 size={18} />
              Clear
            </button>
          )}
        </div>

        {/* Preview */}
        {preview && (
          <div className="mt-5 flex items-start gap-4">
            <img
              src={preview}
              alt="Preview"
              className="rounded-lg border border-white/10 max-h-40 object-contain"
            />
            <div className="grid grid-cols-2 gap-2 text-sm text-gray-300">
              <div className="text-gray-400">File type</div>
              <div className="font-medium">{file?.type || '—'}</div>
              <div className="text-gray-400">Resolution</div>
              <div className="font-medium">{imgMeta.width} × {imgMeta.height}</div>
              <div className="text-gray-400">Size</div>
              <div className="font-medium">{bytesToSize(file?.size || 0)}</div>
              <div className="text-gray-400">Creation date</div>
              <div className="font-medium">{file ? new Date(file.lastModified).toLocaleString() : '—'}</div>
            </div>
          </div>
        )}

        {/* Results */}
        {result && (
          <div className="mt-6 grid gap-4">
            <div className="flex items-center gap-3">
              {result.label === 'AI-Generated' ? (
                <XCircle className="text-red-500" size={22} />
              ) : (
                <CheckCircle className="text-green-500" size={22} />
              )}
              <span
                className={`px-2.5 py-1 rounded-full text-xs font-semibold tracking-wide ${
                  result.label === 'AI-Generated'
                    ? 'bg-red-500/20 text-red-300 border border-red-500/30'
                    : 'bg-green-500/20 text-green-300 border border-green-500/30'
                }`}
              >
                {result.label}
              </span>
            </div>

            <div>
              <div className="flex items-center justify-between mb-2 text-sm text-gray-300">
                <span>Confidence</span>
                <span className="font-semibold">{result.confidence}%</span>
              </div>
              <div className="w-full h-2 rounded-full bg-white/10 overflow-hidden">
                <div
                  className={`h-full ${confidenceColor}`}
                  style={{ width: `${result.confidence}%` }}
                />
              </div>
            </div>

            <p className="text-sm text-gray-300 bg-black/30 border border-white/10 rounded-lg p-3">
              {result.note}
            </p>
          </div>
        )}
      </div>
    </section>
  );
};

export default ImageDetection;
